name: "Build and push Super Mario Docker image with static tag to Docker Hub"

on:
  push:
    branches:
      - main
# env:
#   VERSION: $(( $(cat version.txt) + 1 ))
#   #VERSION: 2

jobs:
  build_push_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Calculate New Version
        id: calculate_version
        run: |
          # Ensure version.txt exists or initialize it
          if [[ ! -f version.txt ]]; then
            echo "0" > version.txt
          fi

          # Read and increment the version
          VERSION=$(cat version.txt)
          if [[ ! $VERSION =~ ^[0-9]+$ ]]; then
            echo "Error: version.txt contains invalid data."
            exit 1
          fi
          NEW_VERSION=$((VERSION + 1))
          echo $NEW_VERSION > version.txt
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t docker.io/eckanas/pakemon:${{ env.VERSION }} .
          docker push docker.io/eckanas/pakemon:${{ env.VERSION }}
